language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls
service_name: travis-pro
repo_token: vshMhMRsGuXnP5zWnL0KC7sZ42LKffSH1